// Generated by scripts/pack-clinic-models.mjs. Do not edit.
export const PACK_URL = 'models/pack/clinic-models.ab6a42b1a44d2448.zst'
export const PACK_TOTAL = 13152224
export const PACK_FILES = [
  { name: 'clinic-shell', offset: 0, length: 86824 },
  { name: 'consultation', offset: 86824, length: 1528980 },
  { name: 'physician-seated', offset: 1615804, length: 2864800 },
  { name: 'patient-seated', offset: 4480604, length: 2314748 },
  { name: 'room-people', offset: 6795352, length: 6356872 },
] as const
